### ISSUE TITLE
Allow users to change font and size

### ISSUE THREAD

**Issue by markcol** [codeperfect95/issue-tracker#1]
### What is the feature you're proposing?

It can be very hard to read the code on high-resolution monitors when using CodePerfect95. Please add the ability to specify font and size for readability and usability.

**Comment by invrainbow** [comment]
With the [22.11 release](https://docs.codeperfect95.com/changelog/22.11) we've added the ability to zoom in and out, which should fix the functional issue of things being too small on high-resolution monitors.

At this stage, the ability to actually literally change the font and size is honestly not a super high priority; there are just too many other higher value things we need to do first.
